version: '3'
#FIXME: docker v18.03 supports version:'3.6'
networks:
  web:
    driver: overlay
volumes:
  consulserver.d:
services:
  cabifyweb:
    image: cabifyweb:v1.0
    depends_on:
      - consulserver
    ports:
      - 8181
    environment:
      - SERVICE_PORTS=8181
      - CONSUL_CLIENT_INTERFACE=eth0
      - CONSUL_BIND_INTERFACE=eth0
    deploy: 
      replicas: 2
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - web
    volumes:
      - consulserver.d:/consulserver.d
  consulserver:
    image: consulserver:v1.0
    environment:
     - CONSUL_BIND_INTERFACE=eth0
    networks:
      - web
    volumes:
      - consulserver.d:/consulserver.d
    deploy:
      placement:
        constraints: [node.role == manager]
  proxy:
    image: dockercloud/haproxy
    depends_on:
      - cabifyweb
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]
