version: '3'
#FIXME: docker v18.03 ya soporta version: '3.6'
services:
  cabifyweb:
   image: cabifyweb:v1.0
   ports:
     - 8181
   environment:
     - SERVICE_PORTS=8181
   deploy:
     replicas: 5
     update_config:
       parallelism: 5
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - cabifyweb
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay